### ISSUE TITLE
[10.0] Why 'auto_install'=True for rma_account, rma_sale, rma_purchase modules ?

### ISSUE THREAD

**Issue by chafique-delli** [ForgeFlow/stock-rma#112]
We do not necessarily want to install all the modules of RMA, that's why, I think that the option 'auto_install' is not necessary.

**Comment by AaronHForgeFlow** [comment]
Yes, I agree, at least for sale and purchases. I think we can change that.

**Comment by AaronHForgeFlow** [comment]
Thanks for the fix :medal_sports:
