### ISSUE TITLE
[10.0]rma_account: searching for invoice lines from the RMA customer, gives nothing

### ISSUE THREAD

**Issue by chafique-delli** [ForgeFlow/stock-rma#113]
If the RMA customer is the primary customer and not the billing contact then the wizard to select invoice lines, finds nothing.
The search domain for invoice lines must use the commercial partner.

**Comment by AaronHForgeFlow** [comment]
The domain now is the following:
      `                     domain="['|',('invoice_id.partner_id', '=', partner_id),('invoice_id.partner_id', 'child_of', partner_id)]"/>`

I will recheck but I think that covers you use case.

**Comment by chafique-delli** [comment]
In fact, I want to talk about the domain for the 'invoice_line_ids' field on the view_rma_add_invoice view of the wizard.
I use the modules of the branch '10.0-imp-rma '
If you want, I can do PR for this branch.

**Comment by AaronHForgeFlow** [comment]
> In fact, I want to talk about the domain for the 'invoice_line_ids' field on the view_rma_add_invoice view of the wizard.
> I use the modules of the branch '10.0-imp-rma '

Hi @chafique-delli perhaps are talking about RMA groups? 

> If you want, I can do PR for this branch.

Sure, if there is a bug better to fix it :) Thank you.

**Comment by chafique-delli** [comment]
Sorry, yes, I want to talk about RMA groups.
You can give me the rights to push on the repository 'stock-rma'.

**Comment by AaronHForgeFlow** [comment]
That is not necessary. You can fork the repository and create a Pull Request to 10.0-imp-rma branch :)

**Comment by chafique-delli** [comment]
OK.

**Comment by chafique-delli** [comment]
https://github.com/Eficent/stock-rma/pull/114

**Comment by AaronHForgeFlow** [comment]
Thanks for fixing this :medal_sports:
