### ISSUE TITLE
[remove headers]refunds and dropship case

### ISSUE THREAD

**Issue by AaronHForgeFlow** [ForgeFlow/stock-rma#14]
There are several issues:

- the rma_account module fails when creating refunds. It depends on crm when it should not. Once crm is installed it's failing because the accounts are not set properly.

- the wizard to create supplier rma from customer rma is not adapted to the new model

**Comment by LoisRForgeFlow** [comment]
second point fixed here: f8266822c1c29a9d29db5c161c44c2439f9878ad

**Comment by LoisRForgeFlow** [comment]
first point fixed here: 170c0b9703c2294f514330d95b77a2562e6a7e6d

**Comment by AaronHForgeFlow** [comment]
@lreficent :1st_place_medal:
