### ISSUE TITLE
[14.0] RMA. Supplier RMAs using Customer like form view

### ISSUE THREAD

**Issue by AaronHForgeFlow** [ForgeFlow/stock-rma#155]
* When creating a return to vendor (supplier rma) Odoo takes me to a "customer" rma view. That is, I see "Customer" instead of vendor, and the link to a "Supplier RMA" instead of a link to a "Customer RMA". Steps to reproduce: create a Customer RMA, approve it, and then create a Supplier RMA using the button in the form view.
![Selection_999(254)](https://user-images.githubusercontent.com/19620251/104619171-da6ebd00-568d-11eb-936b-92f0e86cfd86.png)

**Comment by MateuGForgeFlow** [comment]
@AaronHForgeFlow This issue has been fixed!

**Comment by AaronHForgeFlow** [comment]
Tested and works good!
