### ISSUE TITLE
Issue in routes form view

### ISSUE THREAD

**Issue by LoisRForgeFlow** [ForgeFlow/stock-rma#226]
Versions: at least 14.0

![image](https://user-images.githubusercontent.com/23449160/155117453-284fd34f-674e-4404-ab15-0a661e9b925f.png)

The RMA order lines field is incorrectly positioned.

**Comment by JasminSForgeFlow** [comment]
Issue fixed

- https://github.com/ForgeFlow/stock-rma/pull/227
