### ISSUE TITLE
[11.0] Migration challenges

### ISSUE THREAD

**Issue by max3903** [ForgeFlow/stock-rma#25]
Hi @jbeficent ,

@bodedra identified some challenges to migrate to version 11. Can you review his solution below before he starts development?

Thanks!

**Comment by JordiBForgeFlow** [comment]
Below?

**Comment by max3903** [comment]
@bodedra should be commenting soon with a mapping between v10 and v11 objects...

**Comment by bodedra** [comment]
@max3903 / @jbeficent 

I will update you shortly.

Thank you.

**Comment by bodedra** [comment]
@jbeficent 

procurement.order object has removed from the Odoo 11. So we would like your suggestion on following new relationship.

* Add purchase_id (purchase.order) field into procurement group.

* Procurement group has already linked up with following objects.
    *	procurement.rule,
    *   stock.move,
    * 	stock.picking

* run() and run_scheduler() method moved in procurement.group object.

* _get_stock_move_values() method moved in procurement.rule object. If we need to migration these method then we need to add rma_id (rma.order) and rma_line_id (rma.order.line) fields in it.

We will update more once we reached out other issues.

CC @max3903

**Comment by bodedra** [comment]
@jbeficent 

Need suggestion to handle lot/serial number when pick up "Originating Stock Move". Following is analysis on it.

* lot_ids field removed from stock.move object.

* active_move_line_ids, order_finished_lot_ids introduce by mrp module

* move_line_ids (stock.move.line object) has one2many relationship with stock.move. So we can find lot_id from that table. But question is that what lot_id need to take, if "Originating Stock Move" has more than one move_line_ids ?

CC @max3903

**Comment by JordiBForgeFlow** [comment]
@bodedra In v9 and v10 the procurement.order was just a mechanism to create stock moves and purchase order lines. As a result of creating and running the procurements, the stock moves and PO lines are being linked back to the rma. We expect the same behaviour to continue without procurement orders.

As for the lot/serial number handling, think of this from a functional perspective. A customer calls you and complains about a specific lot/serial number that he has received, and you want to call it back. You need to be able to locate the stock transaction where that lot was shipped, to be able to call it back. So, probably, the user might need to select the given lot/serial from a list of completed stock.move.line?

**Comment by bodedra** [comment]
@jbeficent  Agree for procurement. Would you suggest to modify object or free to touch related object?

Yes. We can provide option to select lot/serial. If we implement it, then how we will handle quantity?

* Based on selected lot/serial or
* No need to touch quantity logic

CC @max3903

**Comment by JordiBForgeFlow** [comment]
@bodedra I do not really understand. Modify what object? If procurements disappear you will need to trigger the equivalent methods in the new model. See, for example, how stock.orderpoint or sale.order works. The procurements are not created, but the 'run' method of procurement.group will need to be run in order to evaluate and create whatever is needed (stock move, purchase order line, etc.).

See https://github.com/odoo/odoo/blob/11.0/addons/sale_stock/models/sale_order.py#L225
