### ISSUE TITLE
[10.0] KeyError: 'picking_id'

### ISSUE THREAD

**Issue by bodedra** [ForgeFlow/stock-rma#26]
Impacted versions: 10.0

Steps to reproduce:

* Create "Supplier RMA Group"
* Click on "Add from stock move" and add one or two moves.
* "Confirm" it

Current behavior:

![screenshot from 2018-02-08 23 06 11](https://user-images.githubusercontent.com/14229503/35988770-69df2d7c-0d25-11e8-8d9f-f8fff07f93a1.png)

**Comment by JordiBForgeFlow** [comment]
@bodedra Please try to dig in to see if you find the root cause.

**Comment by AaronHForgeFlow** [comment]
@bodedra fixed here: https://github.com/Eficent/stock-rma/pull/35
