### ISSUE TITLE
Branch for version 16

### ISSUE THREAD

**Issue by florian-dacosta** [ForgeFlow/stock-rma#321]
Hello,

Is it possible to add a branch for 16.0 version?
I've started a standard migration of main module already, I'll be able to make a PR once the branch is created.

@JordiBForgeFlow @DavidJForgeFlow

**Comment by JordiBForgeFlow** [comment]
@florian-dacosta OK! Will do now. Please take into account my latest commits in 15.0 :)

**Comment by JordiBForgeFlow** [comment]
@florian-dacosta Done. Please migrate using the usual OCA procedure.

**Comment by florian-dacosta** [comment]
Of course
Thanks a lot
