### ISSUE TITLE
RMA order line lot_id missing context

### ISSUE THREAD

**Issue by CasVissers-360ERP** [ForgeFlow/stock-rma#329]
Hi,

While creating a lot from an RMA order line the product is not passed as context (context="{'default_product_id': product_id}") could this be added?

Cas

**Comment by JordiBForgeFlow** [comment]
@CasVissers-360ERP makes sense. 
@DavidJForgeFlow Can you take care of this please?

**Comment by DavidJForgeFlow** [comment]
Done in: #330
