### ISSUE TITLE
[16.0] Missing dependency for purchase_stock in rma_purchase/__manifest__.py

### ISSUE THREAD

**Issue by luke-stdev001** [ForgeFlow/stock-rma#521]
@max3903 we're using these internally and have just noticed a missing dependency here:

https://github.com/ForgeFlow/stock-rma/blob/16.0/rma_purchase/__manifest__.py#L11

for purchase_stock.

**Comment by max3903** [comment]
@JordiBForgeFlow Can you or your team look at this?

**Comment by JordiBForgeFlow** [comment]
Fixed in https://github.com/ForgeFlow/stock-rma/pull/522. Thanks for reporting!
