### ISSUE TITLE
Different selection for receipt_policy on rma.operation and rma.order.line

### ISSUE THREAD

**Issue by andhit-r** [ForgeFlow/stock-rma#7]
Hi guys,

receipt_policy on rma.operation has (1) ordered, (2) received, and (3) no as selection. But rma.order.line has (1) ordered, (2) delivered, and (3) no.

I think rma.order.line's selection are the right one.

PS:
Sorry i could not provide PR since me and my team still working on v8.0. Here is our 8.0 branch https://github.com/open-synergy/stock-rma/tree/8.0 . Feel free to cherry pick.

**Comment by LoisRForgeFlow** [comment]
@andhit-r  Could you point the commit where you fixed this?

**Comment by andhit-r** [comment]
@lreficent  this one 5a00b6ac3a3c238603942fc40b9b2178a1f7a88d

**Comment by LoisRForgeFlow** [comment]
solved. Thanks!
