### ISSUE TITLE
[12.0] rma_repair create a repair order does pass few values

### ISSUE THREAD

**Issue by bodedra** [ForgeFlow/stock-rma#75]
Steps to reproduce:

- Create a sale order, confirm it and deliverer to customer (serial XXXX01)
- Create a Customer RMA, select customer and provide serial XXXX01
- Create a incoming shipment and receive it (serial XXXX01).
- Go back to Customer RMA and click on create a repair order button.
- Change quantity to repair 1 and create a repair order.

Current behaviour:

- Following fields are empty:
   
    - Lot/Serial,
    - Delivery Address and
    - Invoicing Address

Excepted behaviour:

- It should bring necessary information from RMA Line.

**Comment by AaronHForgeFlow** [comment]
Resolved. Thanks @bodedra
