### ISSUE TITLE
[Possible PR] RMA assumes inbound product is same as outbound

### ISSUE THREAD

**Issue by theangryangel** [ForgeFlow/stock-rma#79]
Hi guys,

First off great module, thank you for your work!

Second would you be interested/willing to accept a small patch that would allow the module to create a delivery for a different product than the incoming? I've got something barebones working already, but didn't want to waste time submitting a PR if you weren't interested :)

**Comment by AaronHForgeFlow** [comment]
Hi @theangryangel,

Currently we solve that by creating a SO free of charge (using rma_sale module). Have you tried that?
In any case, if any proposal fits well the current design and adds value to the module we will review it.
Thanks.

**Comment by theangryangel** [comment]
Hadnt actually realised that exists, doh :( I'll investigate. Thank you!
